import { createFileRoute, useParams } from "@tanstack/react-router";
import { SiteLayout } from "@/components/site/SiteLayout";
import { ProgressReportPreview } from "@/components/site/ProgressReportPreview";

export const Route = createFileRoute("/progress-report/$reportId")({
  head: () => ({
    meta: [{ title: "Progress Report — Grandma's Herbals" }],
  }),
  component: ReportViewPage,
});

function ReportViewPage() {
  const { reportId } = useParams({ from: "/progress-report/$reportId" });
  return (
    <SiteLayout>
      <div className="min-h-screen bg-stone-50 py-12">
        <div className="container mx-auto px-4 max-w-4xl">
          <div className="text-center mb-8">
            <h1 className="text-3xl font-cormorant font-bold text-olive-800">Your Progress Report</h1>
            <p className="text-stone-500 mt-2">Generated by Grandma's Herbals</p>
          </div>
          <ProgressReportPreview reportId={reportId} />
        </div>
      </div>
    </SiteLayout>
  );
}
