/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ProgressReportRouteImport } from './routes/progress-report'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BreathworkRouteImport } from './routes/breathwork'
import { Route as ChairStretchRouteImport } from './routes/chair-stretch'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopNotTodayRouteImport } from './routes/shop.not-today'
import { Route as ShopHerbalIvRouteImport } from './routes/shop.herbal-iv'
import { Route as ShopAdultEnhancementRouteImport } from './routes/shop.adult-enhancement'
import { Route as ShopProductIdRouteImport } from './routes/shop.$productId'
import { Route as ProgressReportReportIdRouteImport } from './routes/progress-report.$reportId'
import { Route as WelcomeRouteImport } from './routes/welcome'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressReportRoute = ProgressReportRouteImport.update({
  id: '/progress-report',
  path: '/progress-report',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BreathworkRoute = BreathworkRouteImport.update({
  id: '/breathwork',
  path: '/breathwork',
  getParentRoute: () => rootRouteImport,
} as any)
const ChairStretchRoute = ChairStretchRouteImport.update({
  id: '/chair-stretch',
  path: '/chair-stretch',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopNotTodayRoute = ShopNotTodayRouteImport.update({
  id: '/not-today',
  path: '/not-today',
  getParentRoute: () => ShopRoute,
} as any)
const ShopHerbalIvRoute = ShopHerbalIvRouteImport.update({
  id: '/herbal-iv',
  path: '/herbal-iv',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAdultEnhancementRoute = ShopAdultEnhancementRouteImport.update({
  id: '/adult-enhancement',
  path: '/adult-enhancement',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ShopRoute,
} as any)
const ProgressReportReportIdRoute = ProgressReportReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => ProgressReportRoute,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/breathwork': typeof BreathworkRoute
  '/account': typeof AccountRoute
  '/chair-stretch': typeof ChairStretchRoute
  '/chatbot': typeof ChatbotRoute
  '/intake': typeof IntakeRoute
  '/admin': typeof AdminRoute
  '/assessment': typeof AssessmentRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/consultation': typeof ConsultationRoute
  '/membership': typeof MembershipRoute
  '/progress-report': typeof ProgressReportRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/technology': typeof TechnologyRoute
  '/testimonials': typeof TestimonialsRoute
  '/progress-report/$reportId': typeof ProgressReportReportIdRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop/adult-enhancement': typeof ShopAdultEnhancementRoute
  '/shop/herbal-iv': typeof ShopHerbalIvRoute
  '/shop/not-today': typeof ShopNotTodayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/breathwork': typeof BreathworkRoute
  '/account': typeof AccountRoute
  '/chair-stretch': typeof ChairStretchRoute
  '/chatbot': typeof ChatbotRoute
  '/intake': typeof IntakeRoute
  '/admin': typeof AdminRoute
  '/assessment': typeof AssessmentRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/consultation': typeof ConsultationRoute
  '/membership': typeof MembershipRoute
  '/progress-report': typeof ProgressReportRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/technology': typeof TechnologyRoute
  '/testimonials': typeof TestimonialsRoute
  '/progress-report/$reportId': typeof ProgressReportReportIdRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop/adult-enhancement': typeof ShopAdultEnhancementRoute
  '/shop/herbal-iv': typeof ShopHerbalIvRoute
  '/shop/not-today': typeof ShopNotTodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/breathwork': typeof BreathworkRoute
  '/account': typeof AccountRoute
  '/chair-stretch': typeof ChairStretchRoute
  '/chatbot': typeof ChatbotRoute
  '/intake': typeof IntakeRoute
  '/admin': typeof AdminRoute
  '/assessment': typeof AssessmentRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/consultation': typeof ConsultationRoute
  '/membership': typeof MembershipRoute
  '/progress-report': typeof ProgressReportRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/technology': typeof TechnologyRoute
  '/testimonials': typeof TestimonialsRoute
  '/progress-report/$reportId': typeof ProgressReportReportIdRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop/adult-enhancement': typeof ShopAdultEnhancementRoute
  '/shop/herbal-iv': typeof ShopHerbalIvRoute
  '/shop/not-today': typeof ShopNotTodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/breathwork'
    | '/account'
    | '/chair-stretch'
    | '/chatbot'
    | '/intake'
    | '/admin'
    | '/assessment'
    | '/cart'
    | '/checkout'
    | '/consultation'
    | '/membership'
    | '/progress-report'
    | '/shop'
    | '/sitemap.xml'
    | '/stories'
    | '/technology'
    | '/testimonials'
    | '/progress-report/$reportId'
    | '/shop/$productId'
    | '/shop/adult-enhancement'
    | '/shop/herbal-iv'
    | '/shop/not-today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/breathwork'
    | '/account'
    | '/chair-stretch'
    | '/chatbot'
    | '/intake'
    | '/admin'
    | '/assessment'
    | '/cart'
    | '/checkout'
    | '/consultation'
    | '/membership'
    | '/progress-report'
    | '/shop'
    | '/sitemap.xml'
    | '/stories'
    | '/technology'
    | '/testimonials'
    | '/progress-report/$reportId'
    | '/shop/$productId'
    | '/shop/adult-enhancement'
    | '/shop/herbal-iv'
    | '/shop/not-today'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/breathwork'
    | '/account'
    | '/chair-stretch'
    | '/chatbot'
    | '/intake'
    | '/admin'
    | '/assessment'
    | '/cart'
    | '/checkout'
    | '/consultation'
    | '/membership'
    | '/progress-report'
    | '/shop'
    | '/sitemap.xml'
    | '/stories'
    | '/technology'
    | '/testimonials'
    | '/progress-report/$reportId'
    | '/shop/$productId'
    | '/shop/adult-enhancement'
    | '/shop/herbal-iv'
    | '/shop/not-today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BreathworkRoute: typeof BreathworkRoute
  AccountRoute: typeof AccountRoute
  ChairStretchRoute: typeof ChairStretchRoute
  ChatbotRoute: typeof ChatbotRoute
  IntakeRoute: typeof IntakeRoute
  AdminRoute: typeof AdminRoute
  AssessmentRoute: typeof AssessmentRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ConsultationRoute: typeof ConsultationRoute
  MembershipRoute: typeof MembershipRoute
  ProgressReportRoute: typeof ProgressReportRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoriesRoute: typeof StoriesRoute
  TechnologyRoute: typeof TechnologyRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress-report': {
      id: '/progress-report'
      path: '/progress-report'
      fullPath: '/progress-report'
      preLoaderRoute: typeof ProgressReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breathwork': {
      id: '/breathwork'
      path: '/breathwork'
      fullPath: '/breathwork'
      preLoaderRoute: typeof BreathworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chair-stretch': {
      id: '/chair-stretch'
      path: '/chair-stretch'
      fullPath: '/chair-stretch'
      preLoaderRoute: typeof ChairStretchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/not-today': {
      id: '/shop/not-today'
      path: '/not-today'
      fullPath: '/shop/not-today'
      preLoaderRoute: typeof ShopNotTodayRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/herbal-iv': {
      id: '/shop/herbal-iv'
      path: '/herbal-iv'
      fullPath: '/shop/herbal-iv'
      preLoaderRoute: typeof ShopHerbalIvRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/adult-enhancement': {
      id: '/shop/adult-enhancement'
      path: '/adult-enhancement'
      fullPath: '/shop/adult-enhancement'
      preLoaderRoute: typeof ShopAdultEnhancementRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/progress-report/$reportId': {
      id: '/progress-report/$reportId'
      path: '/$reportId'
      fullPath: '/progress-report/$reportId'
      preLoaderRoute: typeof ProgressReportReportIdRouteImport
      parentRoute: typeof ProgressReportRoute
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProgressReportRouteChildren {
  ProgressReportReportIdRoute: typeof ProgressReportReportIdRoute
}

const ProgressReportRouteChildren: ProgressReportRouteChildren = {
  ProgressReportReportIdRoute: ProgressReportReportIdRoute,
}

const ProgressReportRouteWithChildren = ProgressReportRoute._addFileChildren(
  ProgressReportRouteChildren,
)

interface ShopRouteChildren {
  ShopProductIdRoute: typeof ShopProductIdRoute
  ShopAdultEnhancementRoute: typeof ShopAdultEnhancementRoute
  ShopHerbalIvRoute: typeof ShopHerbalIvRoute
  ShopNotTodayRoute: typeof ShopNotTodayRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopProductIdRoute: ShopProductIdRoute,
  ShopAdultEnhancementRoute: ShopAdultEnhancementRoute,
  ShopHerbalIvRoute: ShopHerbalIvRoute,
  ShopNotTodayRoute: ShopNotTodayRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BreathworkRoute: BreathworkRoute,
  AccountRoute: AccountRoute,
  ChairStretchRoute: ChairStretchRoute,
  ChatbotRoute: ChatbotRoute,
  IntakeRoute: IntakeRoute,
  AdminRoute: AdminRoute,
  WelcomeRoute: WelcomeRoute,
  AssessmentRoute: AssessmentRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ConsultationRoute: ConsultationRoute,
  MembershipRoute: MembershipRoute,
  ProgressReportRoute: ProgressReportRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoriesRoute: StoriesRoute,
  TechnologyRoute: TechnologyRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
